### PR TITLE
US9 - Setup Email

### LINKED ISSUE #61: US9: Setup and edit email account information in the app to send messages
As a user, 
I want to setup and edit email account info, 
So that I can configure the app to know which email to send emails from

Tasks:
- [x] - #92  
- [x] - #93  
- [x] - #94 
- [x] - #95

### PR DESCRIPTION
**Pull request by Von-Taylor**

### CODE REVIEW

**Review by thELanee — APPROVED** [review]
ikz

**Review by quistian241 — APPROVED** [review]
gawsh this was hard but good work team

**Review by kate-romero — APPROVED** [review]
super

**Review by aaamarque — APPROVED** [review]
looks good

**Review by jezebelatucsd — APPROVED** [review]
good

**Pull request merged**
